### ISSUE TITLE
DE1 Soc Audio

### ISSUE THREAD

**Issue by larryjol** [bsteinsbo/DE1-SoC-Sound#2]
Dear Bsteinsbo,

I am begginer in SoC devices, i have the DE1 SoC and i have to implement a aplication that play a wav file from sd card memory, i try with the LXDE system but there is not audio output. I would like to ask you about how can access to sd file and implement the audio core. Thanks

**Comment by bsteinsbo** [comment]
If I understand your assignement correctly, the steps you need to take are:

a. Implement i2s interface in the FPGA fabric.  The RTL in this repository should help you do that.
b. Implement an ALSA driver for Linux to interface to your hardware.  Again, the driver in this repository could be at least a starting point for that.
c. Use standard Linux functionality to read files from an SD card play them using e.g. "aplay".  This part is trivial when you have working hardware with corresponding ALSA driver.

In theory you could also do everything from the FPGA side, e.g. starting with the audio example on the Terasic CD.  But I believe interfacing the SD card would be a major pain if you choose to take this path.

-br

Bjarne

**Comment by rathi2** [comment]
Hello , I am trying the project on DE1 SOC board to implement a application that play a wav file from SD card memory. But I am not able to succeed in SD card NIOSII implementation.  Can you help me ?

**Comment by bsteinsbo** [comment]
Hi,

Sorry, I have absolutely zero NIOS experience.

BR,
Bjarne
